image: docker:latest
services:
  - docker:dind

variables:
  RELEASE_IMAGE: $CI_REGISTRY/$CI_PROJECT_PATH:latest

stages:
  - release

release:
  stage: release
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build --pull -t $RELEASE_IMAGE .
    - docker push $RELEASE_IMAGE

